### ISSUE TITLE
unable to parse content - \HookyQR.beautify-1.0.0\schema\beautifyrc.json'

### ISSUE THREAD

**Issue by iliran11** [HookyQR/VSCodeBeautify#119]
* **Windows Version:** windows 10 version 1607 
* **VS Code:** 1.10.2 
* **beautify Version**: 1.0.0

## Action performed
Open any javascript file, and get this warning:
```
file: 'file:///c%3A/projects/banking/.jsbeautifyrc'
severity: 'Warning'
message: 'Unable to parse content from 'c:\Users\liranc\.vscode\extensions\HookyQR.beautify-1.0.0\schema\beautifyrc.json': .'
at: '1,1'
source: ''
```

content of my .jsbeautifyrc:
```json
{
  "indent_size": 4,
  "indent_char": " ",
  "indent_level": 0,
  "indent_with_tabs": false,
  "preserve_newlines": true,
  "max_preserve_newlines": 2,
  "jslint_happy": true
}
```

.jsbeautifyrc seems to be respected, but i am not sure what is the impact of this warning
and why it appears

thanks!

**Comment by HookyQR** [comment]
Fixed. New version released. Thanks.

**Comment by schmuli** [comment]
@HookyQR, Just got the new version and still getting the parse error, you have an extra comma: 
https://github.com/HookyQR/VSCodeBeautify/blob/master/schema/beautifyrc.json#L39

**Comment by HookyQR** [comment]
Version 1.0.1?

**Comment by schmuli** [comment]
Sorry, it was all happening simultaneously, the file updated on GitHub at the same second as I was adding the comment.

**Comment by schmuli** [comment]
Sorry for any confusion, installed 1.0.1 and no more errors. Thanks for your great work and speedy responses.
